name: Build MP3 Player

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    name: Build EX-word addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download & Build
        run: |
          curl -sSfL https://github.com/MaxSignal/buildscripts/releases/download/Linux/devkitPro.tar.gz | tar -zxf - -C ..
          DEVKITPRO="${GITHUB_WORKSPACE}/../devkitPro" DEVKITSH4="${GITHUB_WORKSPACE}/../devkitPro/devkitSH4" PATH="${GITHUB_WORKSPACE}/../devkitPro/tools/bin:${GITHUB_WORKSPACE}/../devkitPro/devkitSH4/bin:$PATH" make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exword-mp3player-build
          path: build/
